In [1]:
from itertools import count
from collections import defaultdict
from scipy.sparse import csr
import numpy as np
import pandas as pd
import numpy as np
from sklearn.feature_extraction import DictVectorizer
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
from tqdm import tqdm_notebook as tqdm

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
cols = ['user','item','rating','timestamp']

train = pd.read_csv('data/ua.base',delimiter='\t',names = cols)
test = pd.read_csv('data/ua.test',delimiter='\t',names = cols)

In [26]:
train['user'].values

array([  1,   1,   1, ..., 943, 943, 943], dtype=int64)

In [86]:
def vectorize_dic(dic,ix=None,p=None,n=0,g=0):
    """
    dic -- dictionary of feature lists. Keys are the name of features
    ix -- index generator (default None)
    p -- dimension of feature space (number of columns in the sparse matrix) (default None)
    """
    if ix==None:
        ix = dict()

    nz = n * g

    col_ix = np.empty(nz,dtype = int)
    col_ix_key =  [''] * nz

    i = 0
    debug=0
    for k,lis in dic.items():
        print(len(lis))
        for t in range(len(lis)):
            # ix[value_user] = count ++ 
            key = str(lis[t]) + str(k)
            ix[key] = ix.get(key,0) + 1
            col_ix[i+t*g] = ix[key]
            col_ix_key[i+t*g] = key
            debug = (i+t*g)
        print(debug)
        i += 1
    print(col_ix.shape)
    print(col_ix[col_ix.shape[0] -1 ])
    print(col_ix_key[col_ix.shape[0] -1 ])
    row_ix = np.repeat(np.arange(0,n),g)

    data = np.ones(nz)
    if p == None:
        p = len(ix)

    print(p)
    print(col_ix)
    ixx = np.where(col_ix < p)
    print(ixx)
    print(data.shape)
    print(data[ixx].shape)
    print(row_ix[ixx])
    print(col_ix[ixx])
    return csr.csr_matrix((data[ixx],(row_ix[ixx],col_ix[ixx])),shape=(n,p)),ix

In [87]:
x_train,ix = vectorize_dic({'users':test['user'].values,
                            'items':test['item'].values},n=len(train.index),g=2)

9430
18858
9430
18859
(181140,)
0

2072
[1 1 2 ... 0 0 0]
(array([     0,      1,      2, ..., 181137, 181138, 181139], dtype=int64),)
(181140,)
(181133,)
[    0     0     1 ... 90568 90569 90569]
[1 1 2 ... 0 0 0]


In [9]:
row_ix = np.repeat(np.arange(0,100),2)

In [11]:
print(row_ix.shape)

(200,)


In [13]:
row_ix

array([ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,
        8,  9,  9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16,
       17, 17, 18, 18, 19, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 25,
       25, 26, 26, 27, 27, 28, 28, 29, 29, 30, 30, 31, 31, 32, 32, 33, 33,
       34, 34, 35, 35, 36, 36, 37, 37, 38, 38, 39, 39, 40, 40, 41, 41, 42,
       42, 43, 43, 44, 44, 45, 45, 46, 46, 47, 47, 48, 48, 49, 49, 50, 50,
       51, 51, 52, 52, 53, 53, 54, 54, 55, 55, 56, 56, 57, 57, 58, 58, 59,
       59, 60, 60, 61, 61, 62, 62, 63, 63, 64, 64, 65, 65, 66, 66, 67, 67,
       68, 68, 69, 69, 70, 70, 71, 71, 72, 72, 73, 73, 74, 74, 75, 75, 76,
       76, 77, 77, 78, 78, 79, 79, 80, 80, 81, 81, 82, 82, 83, 83, 84, 84,
       85, 85, 86, 86, 87, 87, 88, 88, 89, 89, 90, 90, 91, 91, 92, 92, 93,
       93, 94, 94, 95, 95, 96, 96, 97, 97, 98, 98, 99, 99])

In [20]:
np.where(row_ix > 10)[0].shape

(178,)